# Generated by Django 6.0.1 on 2026-01-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mfa_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
