# Generated by Django 6.0.1 on 2026-01-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("time_limit", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=1)),
                ("questions", models.JSONField(default=list)),
            ],
        ),
    ]
