# Generated by Django 6.0.1 on 2026-01-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_options_remove_assessment_course_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together=set(),
        ),
    ]
