# Generated by Django 6.0.1 on 2026-01-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_codingexercise"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course_id",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
